"""add_priority

Revision ID: 2d3b7bbab0c9
Revises: abbdeae7f462
Create Date: 2026-06-16 19:47:15.236704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3b7bbab0c9'
down_revision: Union[str, Sequence[str], None] = 'abbdeae7f462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'priority')
    # ### end Alembic commands ###
